<section class="grammar-card-group">

選出最適合空格的受格。題目為原創 TOEIC-style 商務情境句。

{% assign object_options = "Me|You|Him|Her|It|Us|Them" %}

{% include grammar/pronoun-card.html title="Question 1" question="The manager asked ___ to prepare the handouts." translation="經理請我準備講義。" options=object_options answer="Me" analysis='[{"word":"Me","label":"Obj","desc":"I 的受格，放在動詞 asked 後面。"},{"word":"asked","label":"V","desc":"主要動詞。"},{"word":"to prepare the handouts","label":"V","desc":"不定詞片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 2" question="The receptionist will call ___ when the package arrives." translation="包裹到達時，接待員會打電話給你。" options=object_options answer="You" analysis='[{"word":"You","label":"Obj","desc":"You 的主格和受格同形。"},{"word":"will call","label":"V","desc":"未來式動詞。"},{"word":"when the package arrives","label":"Time","desc":"時間副詞子句。"}]' %}
{% include grammar/pronoun-card.html title="Question 3" question="Please remind ___ about the 3 p.m. appointment." translation="請提醒他下午三點的約會。" options=object_options answer="Him" analysis='[{"word":"Him","label":"Obj","desc":"He 的受格，放在 remind 後面。"},{"word":"remind","label":"V","desc":"提醒。"},{"word":"about the appointment","label":"Prep","desc":"介系詞片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 4" question="The client thanked ___ for the quick response." translation="客戶感謝她快速回覆。" options=object_options answer="Her" analysis='[{"word":"Her","label":"Obj","desc":"She 的受格，放在 thanked 後面。"},{"word":"thanked","label":"V","desc":"主要動詞。"},{"word":"for the quick response","label":"Prep","desc":"原因片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 5" question="The technician checked ___ before the meeting began." translation="技術人員在會議開始前檢查了它。" options=object_options answer="It" analysis='[{"word":"It","label":"Obj","desc":"It 作受格，指設備或物品。"},{"word":"checked","label":"V","desc":"主要動詞。"},{"word":"before the meeting began","label":"Time","desc":"時間副詞子句。"}]' %}
{% include grammar/pronoun-card.html title="Question 6" question="The director invited ___ to join the planning session." translation="主管邀請我們參加規劃會議。" options=object_options answer="Us" analysis='[{"word":"Us","label":"Obj","desc":"We 的受格。"},{"word":"invited","label":"V","desc":"主要動詞。"},{"word":"to join the planning session","label":"V","desc":"不定詞片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 7" question="The coordinator sent ___ the revised schedule." translation="協調人寄給他們修訂後的時程表。" options=object_options answer="Them" analysis='[{"word":"Them","label":"Obj","desc":"They 的受格。"},{"word":"sent","label":"V","desc":"可接間接受詞和直接受詞。"},{"word":"the revised schedule","label":"N","desc":"直接受詞。"}]' %}
{% include grammar/pronoun-card.html title="Question 8" question="Could you send ___ the meeting link?" translation="你可以寄會議連結給我嗎？" options=object_options answer="Me" analysis='[{"word":"Me","label":"Obj","desc":"作 send 的間接受詞。"},{"word":"send","label":"V","desc":"主要動詞。"},{"word":"the meeting link","label":"N","desc":"直接受詞。"}]' %}
{% include grammar/pronoun-card.html title="Question 9" question="The security guard directed ___ to the visitor entrance." translation="保全引導他到訪客入口。" options=object_options answer="Him" analysis='[{"word":"Him","label":"Obj","desc":"男性單數受格。"},{"word":"directed","label":"V","desc":"引導。"},{"word":"to the visitor entrance","label":"Place","desc":"地點片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 10" question="I will forward the invoice to ___ this afternoon." translation="我今天下午會把發票轉寄給你。" options=object_options answer="You" analysis='[{"word":"You","label":"Obj","desc":"介系詞 to 後面使用受格。"},{"word":"will forward","label":"V","desc":"未來式。"},{"word":"this afternoon","label":"Time","desc":"時間片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 11" question="The software update should fix ___ automatically." translation="軟體更新應該會自動修復它。" options=object_options answer="It" analysis='[{"word":"It","label":"Obj","desc":"指問題或系統錯誤。"},{"word":"should fix","label":"V","desc":"should 加原形動詞。"},{"word":"automatically","label":"Adj","desc":"副詞，表示自動地。"}]' %}
{% include grammar/pronoun-card.html title="Question 12" question="The trainer showed ___ how to use the new scanner." translation="訓練員示範給我們看如何使用新掃描器。" options=object_options answer="Us" analysis='[{"word":"Us","label":"Obj","desc":"We 的受格，作 showed 的受詞。"},{"word":"showed","label":"V","desc":"主要動詞。"},{"word":"how to use the new scanner","label":"N","desc":"名詞子句片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 13" question="The HR team contacted ___ about the orientation schedule." translation="人資團隊聯絡他們討論新人訓練時程。" options=object_options answer="Them" analysis='[{"word":"Them","label":"Obj","desc":"They 的受格。"},{"word":"contacted","label":"V","desc":"主要動詞。"},{"word":"about the orientation schedule","label":"Prep","desc":"介系詞片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 14" question="The supervisor praised ___ for finishing the project early." translation="主管稱讚她提早完成專案。" options=object_options answer="Her" analysis='[{"word":"Her","label":"Obj","desc":"女性單數受格。"},{"word":"praised","label":"V","desc":"稱讚。"},{"word":"for finishing the project early","label":"Prep","desc":"原因片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 15" question="Please give ___ a copy of the contract." translation="請給他一份合約副本。" options=object_options answer="Him" analysis='[{"word":"Him","label":"Obj","desc":"作 give 的間接受詞。"},{"word":"give","label":"V","desc":"可接雙受詞。"},{"word":"a copy of the contract","label":"N","desc":"直接受詞。"}]' %}
{% include grammar/pronoun-card.html title="Question 16" question="The consultant advised ___ to reduce operating costs." translation="顧問建議我們降低營運成本。" options=object_options answer="Us" analysis='[{"word":"Us","label":"Obj","desc":"We 的受格。"},{"word":"advised","label":"V","desc":"建議。"},{"word":"to reduce operating costs","label":"V","desc":"不定詞片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 17" question="The shipping clerk packed ___ carefully." translation="出貨人員小心地包裝它。" options=object_options answer="It" analysis='[{"word":"It","label":"Obj","desc":"指貨品或包裹。"},{"word":"packed","label":"V","desc":"主要動詞。"},{"word":"carefully","label":"Adj","desc":"副詞，修飾 packed。"}]' %}
{% include grammar/pronoun-card.html title="Question 18" question="The CEO congratulated ___ on the successful launch." translation="執行長祝賀他們成功上市。" options=object_options answer="Them" analysis='[{"word":"Them","label":"Obj","desc":"They 的受格。"},{"word":"congratulated","label":"V","desc":"祝賀。"},{"word":"on the successful launch","label":"Prep","desc":"介系詞片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 19" question="The assistant reminded ___ to sign the visitor log." translation="助理提醒我簽訪客登記表。" options=object_options answer="Me" analysis='[{"word":"Me","label":"Obj","desc":"I 的受格。"},{"word":"reminded","label":"V","desc":"提醒。"},{"word":"to sign the visitor log","label":"V","desc":"不定詞片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 20" question="The branch manager introduced ___ to the regional director." translation="分店經理把她介紹給區域主管。" options=object_options answer="Her" analysis='[{"word":"Her","label":"Obj","desc":"She 的受格。"},{"word":"introduced","label":"V","desc":"介紹。"},{"word":"to the regional director","label":"Prep","desc":"介系詞片語。"}]' %}

</section>
