<section class="grammar-card-group">

選出最適合空格的人稱代名詞。題目為原創 TOEIC-style 商務情境句。

{% assign subject_options = "I|You|He|She|It|We|They" %}

{% include grammar/pronoun-card.html title="Question 1" question="___ will attend the budget meeting at 9 a.m." translation="我會參加上午九點的預算會議。" options=subject_options answer="I" analysis='[{"word":"I","label":"Subj","desc":"主格人稱代名詞，表示說話者本人。"},{"word":"will attend","label":"V","desc":"未來式動詞片語。"},{"word":"the budget meeting","label":"N","desc":"受詞名詞片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 2" question="___ are required to submit the form by Friday." translation="你必須在星期五前提交表格。" options=subject_options answer="You" analysis='[{"word":"You","label":"Subj","desc":"主格人稱代名詞，可表示你或你們。"},{"word":"are required","label":"V","desc":"被動語態，表示被要求。"},{"word":"by Friday","label":"Time","desc":"截止時間。"}]' %}
{% include grammar/pronoun-card.html title="Question 3" question="___ is responsible for training new staff members." translation="他負責訓練新進員工。" options=subject_options answer="He" analysis='[{"word":"He","label":"Subj","desc":"主格人稱代名詞，指男性單數。"},{"word":"is responsible for","label":"Be","desc":"表示負責某事。"},{"word":"training new staff members","label":"V","desc":"動名詞片語作介系詞受詞。"}]' %}
{% include grammar/pronoun-card.html title="Question 4" question="___ has prepared the sales report for the director." translation="她已經為主管準備好銷售報告。" options=subject_options answer="She" analysis='[{"word":"She","label":"Subj","desc":"主格人稱代名詞，指女性單數。"},{"word":"has prepared","label":"V","desc":"現在完成式。"},{"word":"the sales report","label":"N","desc":"受詞名詞片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 5" question="___ needs to be repaired before the presentation." translation="它需要在簡報前修好。" options=subject_options answer="It" analysis='[{"word":"It","label":"Subj","desc":"主格人稱代名詞，指物品、設備或事情。"},{"word":"needs to be repaired","label":"V","desc":"表示需要被修理。"},{"word":"before the presentation","label":"Time","desc":"時間副詞片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 6" question="___ have reviewed the contract carefully." translation="我們已經仔細審閱合約。" options=subject_options answer="We" analysis='[{"word":"We","label":"Subj","desc":"主格人稱代名詞，表示我們。"},{"word":"have reviewed","label":"V","desc":"現在完成式。"},{"word":"the contract","label":"N","desc":"受詞名詞。"}]' %}
{% include grammar/pronoun-card.html title="Question 7" question="___ are waiting in the reception area." translation="他們正在接待區等候。" options=subject_options answer="They" analysis='[{"word":"They","label":"Subj","desc":"主格人稱代名詞，表示他們或它們。"},{"word":"are waiting","label":"V","desc":"現在進行式。"},{"word":"in the reception area","label":"Place","desc":"地點副詞片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 8" question="___ should contact the supplier directly." translation="你應該直接聯絡供應商。" options=subject_options answer="You" analysis='[{"word":"You","label":"Subj","desc":"句子的主詞，表示聽話者。"},{"word":"should contact","label":"V","desc":"should 加原形動詞表示建議。"},{"word":"the supplier","label":"N","desc":"受詞名詞。"}]' %}
{% include grammar/pronoun-card.html title="Question 9" question="___ was promoted to regional manager last month." translation="他上個月被升任為區域經理。" options=subject_options answer="He" analysis='[{"word":"He","label":"Subj","desc":"男性單數主詞。"},{"word":"was promoted","label":"V","desc":"過去式被動語態。"},{"word":"last month","label":"Time","desc":"過去時間。"}]' %}
{% include grammar/pronoun-card.html title="Question 10" question="___ is available in three different sizes." translation="它有三種不同尺寸可供選擇。" options=subject_options answer="It" analysis='[{"word":"It","label":"Subj","desc":"指產品或物品。"},{"word":"is available","label":"Be","desc":"表示可取得、可使用。"},{"word":"in three different sizes","label":"Prep","desc":"介系詞片語補充規格。"}]' %}
{% include grammar/pronoun-card.html title="Question 11" question="___ plan to launch the campaign next quarter." translation="我們計畫下季推出活動。" options=subject_options answer="We" analysis='[{"word":"We","label":"Subj","desc":"表示說話者所在的團隊。"},{"word":"plan to launch","label":"V","desc":"plan to 加原形動詞。"},{"word":"next quarter","label":"Time","desc":"未來時間。"}]' %}
{% include grammar/pronoun-card.html title="Question 12" question="___ have not received the updated invoice yet." translation="他們尚未收到更新後的發票。" options=subject_options answer="They" analysis='[{"word":"They","label":"Subj","desc":"複數主詞。"},{"word":"have not received","label":"V","desc":"現在完成式否定。"},{"word":"the updated invoice","label":"N","desc":"受詞名詞片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 13" question="___ am checking the reservation details now." translation="我現在正在確認訂位細節。" options=subject_options answer="I" analysis='[{"word":"I","label":"Subj","desc":"只有 I 搭配 am。"},{"word":"am checking","label":"V","desc":"現在進行式。"},{"word":"the reservation details","label":"N","desc":"受詞名詞片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 14" question="___ is leading the product demonstration today." translation="她今天負責帶領產品展示。" options=subject_options answer="She" analysis='[{"word":"She","label":"Subj","desc":"女性單數主詞。"},{"word":"is leading","label":"V","desc":"現在進行式。"},{"word":"the product demonstration","label":"N","desc":"受詞名詞片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 15" question="___ must wear identification badges in the facility." translation="你們在設施內必須配戴識別證。" options=subject_options answer="You" analysis='[{"word":"You","label":"Subj","desc":"可表示複數的你們。"},{"word":"must wear","label":"V","desc":"must 加原形動詞表示義務。"},{"word":"identification badges","label":"N","desc":"受詞名詞片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 16" question="___ is printed on recycled paper." translation="它是印在再生紙上。" options=subject_options answer="It" analysis='[{"word":"It","label":"Subj","desc":"指文件或手冊。"},{"word":"is printed","label":"V","desc":"現在式被動語態。"},{"word":"on recycled paper","label":"Prep","desc":"介系詞片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 17" question="___ were invited to the annual conference." translation="他們受邀參加年度會議。" options=subject_options answer="They" analysis='[{"word":"They","label":"Subj","desc":"複數主詞搭配 were。"},{"word":"were invited","label":"V","desc":"過去式被動語態。"},{"word":"to the annual conference","label":"Prep","desc":"介系詞片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 18" question="___ are updating the customer database this week." translation="我們本週正在更新客戶資料庫。" options=subject_options answer="We" analysis='[{"word":"We","label":"Subj","desc":"表示我們這個團隊。"},{"word":"are updating","label":"V","desc":"現在進行式。"},{"word":"the customer database","label":"N","desc":"受詞名詞片語。"}]' %}
{% include grammar/pronoun-card.html title="Question 19" question="___ has arranged transportation for the guests." translation="她已經為訪客安排交通。" options=subject_options answer="She" analysis='[{"word":"She","label":"Subj","desc":"女性單數主詞。"},{"word":"has arranged","label":"V","desc":"現在完成式。"},{"word":"transportation","label":"N","desc":"受詞名詞。"}]' %}
{% include grammar/pronoun-card.html title="Question 20" question="___ will send the agenda after lunch." translation="我會在午餐後寄出議程。" options=subject_options answer="I" analysis='[{"word":"I","label":"Subj","desc":"主格人稱代名詞，表示我。"},{"word":"will send","label":"V","desc":"未來式。"},{"word":"the agenda","label":"N","desc":"受詞名詞。"}]' %}

</section>
